#!/usr/bin/env bash
#
# hypratomic firstboot — runs once per user on first graphical login.
# Idempotent: the marker file guards against re-running.
#
# Triggered by /etc/xdg/autostart/hypratomic-firstboot.desktop.
#
set -euo pipefail

MARKER="${HOME}/.local/state/hypratomic-bootstrap.done"
[[ -f "$MARKER" ]] && exit 0

log() { logger -t hypratomic-firstboot "$*"; printf '==> %s\n' "$*" >&2; }

log "First-boot setup for user $USER"

# --- Skel sync: force-replace autogenerated files, else non-destructive copy ---
src="/etc/skel"
if [[ -d "$src" ]]; then
    # Replace Hyprland's autogenerated placeholder if present.
    target="$HOME/.config/hypr/hyprland.conf"
    if [[ -f "$target" ]] && grep -q '^autogenerated = 1' "$target" 2>/dev/null; then
        log "Replacing autogenerated ~/.config/hypr/hyprland.conf"
        mkdir -p "$(dirname "$target")"
        cp -f "$src/.config/hypr/hyprland.conf" "$target"
    fi

    # Non-destructive bulk copy for everything else.
    shopt -s dotglob nullglob
    for entry in "$src"/*; do
        name="$(basename "$entry")"
        [[ "$name" == "." || "$name" == ".." ]] && continue
        if [[ -d "$entry" ]]; then
            mkdir -p "$HOME/$name"
            cp -rn "$entry/." "$HOME/$name/" 2>/dev/null || true
        else
            [[ -e "$HOME/$name" ]] || cp "$entry" "$HOME/$name"
        fi
    done
    shopt -u dotglob nullglob
fi

# --- Enable dormant user systemd units ---
systemctl --user daemon-reload 2>/dev/null || true
systemctl --user enable rclone-proton-drive.service 2>/dev/null || true

# --- Reload Hyprland if it's running, so new config takes effect immediately ---
if [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] && command -v hyprctl >/dev/null; then
    hyprctl reload >/dev/null 2>&1 || true
fi

# --- Drop marker so this never runs again ---
mkdir -p "$(dirname "$MARKER")"
touch "$MARKER"
log "Done. Marker: $MARKER"
